// <auto-generated />
using System;
using HalalBank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HalalBank.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@email.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "$2a$11$XUpNUQrDg84IpI9Fdrd3.uTBHDpCy2Og/Eaf4396yew/kQZKC7toS",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@email.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "$2a$11$XUpNUQrDg84IpI9Fdrd3.uTBHDpCy2Og/Eaf4396yew/kQZKC7toS",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.wilson@email.com",
                            FirstName = "Bob",
                            LastName = "Wilson",
                            Password = "$2a$11$XUpNUQrDg84IpI9Fdrd3.uTBHDpCy2Og/Eaf4396yew/kQZKC7toS",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("HalalBank.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HalalBank.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NextPaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SubscriptionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingCycle = "Monthly",
                            Category = "Streaming",
                            CustomerId = 1,
                            NextPaymentDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 15.99m,
                            ProviderName = "Netflix",
                            Status = "Active",
                            SubscriptionNumber = "SUB-48291",
                            SubscriptionType = "Streaming"
                        },
                        new
                        {
                            Id = 2,
                            BillingCycle = "Monthly",
                            Category = "Music",
                            CustomerId = 1,
                            NextPaymentDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 9.99m,
                            ProviderName = "Spotify",
                            Status = "Active",
                            SubscriptionNumber = "SUB-73518",
                            SubscriptionType = "Music"
                        },
                        new
                        {
                            Id = 3,
                            BillingCycle = "Monthly",
                            Category = "Utilities",
                            CustomerId = 2,
                            NextPaymentDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 120.00m,
                            ProviderName = "Electricity Bill",
                            Status = "Active",
                            SubscriptionNumber = "SUB-20946",
                            SubscriptionType = "Electricity"
                        },
                        new
                        {
                            Id = 4,
                            BillingCycle = "Monthly",
                            Category = "Utilities",
                            CustomerId = 2,
                            NextPaymentDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 59.99m,
                            ProviderName = "Internet",
                            Status = "Active",
                            SubscriptionNumber = "SUB-66831",
                            SubscriptionType = "Internet"
                        },
                        new
                        {
                            Id = 5,
                            BillingCycle = "Yearly",
                            Category = "Software",
                            CustomerId = 3,
                            NextPaymentDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 99.99m,
                            ProviderName = "Cloud Storage",
                            Status = "Active",
                            SubscriptionNumber = "SUB-11387",
                            SubscriptionType = "Software"
                        });
                });

            modelBuilder.Entity("HalalBank.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DefaultBillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Streaming",
                            DefaultBillingCycle = "Monthly",
                            DefaultPrice = 15.99m,
                            Name = "Netflix Premium"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Music",
                            DefaultBillingCycle = "Monthly",
                            DefaultPrice = 9.99m,
                            Name = "Spotify"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Health",
                            DefaultBillingCycle = "Monthly",
                            DefaultPrice = 49.99m,
                            Name = "Gym Membership"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Utilities",
                            DefaultBillingCycle = "Monthly",
                            DefaultPrice = 59.99m,
                            Name = "Internet Bill"
                        });
                });

            modelBuilder.Entity("HalalBank.Domain.Entities.Payment", b =>
                {
                    b.HasOne("HalalBank.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HalalBank.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("HalalBank.Domain.Entities.Customer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HalalBank.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("HalalBank.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
